### PR TITLE
fix: default to showing the progress bar

### PR DESCRIPTION
**Pull request by shetzel**
### What does this PR do?
Change progress bar default to show rather than detect support as default.

### What issues does this PR fix or reference?
@W-13701811@
https://github.com/forcedotcom/cli/issues/2276
https://github.com/forcedotcom/cli/issues/2249

### CODE REVIEW

**Comment by mshanemc** [comment]
qa notes: works on my machine in a TTY environment.

case `SF_USE_PROGRESS_BAR`
true: shows bar
false: hides bar
undefined: shows bar

The previous version, in the `undefined` case, doesn't set the noTTY option and let oclif decide based TTY-ness and the `process.env.TERM === 'dumb'` and this PR will eliminate that behavior since it's always passing an option.  
 
https://github.com/oclif/core/blob/fbdf25b9eff4c7b8e3dd36ec29a6e035ce2ce5a6/src/cli-ux/styled/progress.ts#L5-L6

**Review by mshanemc — APPROVED** [review]

**Comment by shabu74** [comment]
But it is no happening in GitLab CICD pipeline :(

**Comment by mcarvin8** [comment]
Confirming this is fixed in a GitLab CI/CD pipeline via sf version 2.1.7. Thanks!

gitlab


```
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.0",
  "osVersion": "Linux 5.15.108",
  "shell": "ash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)",
    "sfdx-git-delta 5.24.0 (user)"
  ]
}
```

**Comment by shabu74** [comment]
Yes it appeared. But like this :

Deploy ID: 0Af9h000006GqfBCAS
Status: {status} | 0/0 Components (Errors:{errorCount}) {testInfo}
Status: Waiting | 0/0 Components (Errors:{errorCount}) {testInfo}
Status: Waiting | 0/0 Components (Errors:{errorCount}) {testInfo}
Status: Succeeded | 3/3 Components (Errors:0) | 0/0 Tests (Errors:0)
Validated Source
=========================================================================================================================
| State   Name            Type             Path                                                                           
| ─────── ─────────────── ──────────────── ────────────────────────────────────────────────────────────────────────────── 
| Changed Case.Assistance RecordType       force-app/main/default/objects/Case/recordTypes/Assistance.recordType-meta.xml 
| Changed CaseReason      StandardValueSet force-app/main/default/standardValueSets/CaseReason.standardValueSet-meta.xml  
| Changed CaseType        StandardValueSet force-app/main/default/standardValueSets/CaseType.standardValueSet-meta.xml    
Warning: You can ensure tests run by specifying `--test-level` and setting it to `RunSpecifiedTests`, `RunLocalTests` or `RunAllTestsInOrg`.

**Pull request merged**
